//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace AutoDealer.DB.its_honda
{

    [Persistent(@"branches")]
    public partial class BranchesModel : XPLiteObject
    {
        long fid;
        [Key(true)]
        public long id
        {
            get { return fid; }
            set { SetPropertyValue<long>("id", ref fid, value); }
        }
        string fnama_branch;
        [Size(255)]
        public string nama_branch
        {
            get { return fnama_branch; }
            set { SetPropertyValue<string>("nama_branch", ref fnama_branch, value); }
        }
        string falamat;
        [Size(255)]
        public string alamat
        {
            get { return falamat; }
            set { SetPropertyValue<string>("alamat", ref falamat, value); }
        }
        string fno_telepon;
        [Size(255)]
        public string no_telepon
        {
            get { return fno_telepon; }
            set { SetPropertyValue<string>("no_telepon", ref fno_telepon, value); }
        }
        string flat;
        [Size(255)]
        public string lat
        {
            get { return flat; }
            set { SetPropertyValue<string>("lat", ref flat, value); }
        }
        string flong1;
        [Size(255)]
        [Persistent(@"long")]
        public string long1
        {
            get { return flong1; }
            set { SetPropertyValue<string>("long1", ref flong1, value); }
        }
        string femail;
        [Size(255)]
        public string email
        {
            get { return femail; }
            set { SetPropertyValue<string>("email", ref femail, value); }
        }
        string ffax;
        [Size(255)]
        public string fax
        {
            get { return ffax; }
            set { SetPropertyValue<string>("fax", ref ffax, value); }
        }
        DateTime fcreatedAt;
        public DateTime createdAt
        {
            get { return fcreatedAt; }
            set { SetPropertyValue<DateTime>("createdAt", ref fcreatedAt, value); }
        }
        DateTime fupdatedAt;
        public DateTime updatedAt
        {
            get { return fupdatedAt; }
            set { SetPropertyValue<DateTime>("updatedAt", ref fupdatedAt, value); }
        }
        DateTime fdeletedAt;
        public DateTime deletedAt
        {
            get { return fdeletedAt; }
            set { SetPropertyValue<DateTime>("deletedAt", ref fdeletedAt, value); }
        }
        int fversion;
        public int version
        {
            get { return fversion; }
            set { SetPropertyValue<int>("version", ref fversion, value); }
        }
        [Association(@"BranchmanagersModelReferencesBranchesModel")]
        public XPCollection<BranchmanagersModel> BranchmanagersModelCollection { get { return GetCollection<BranchmanagersModel>("BranchmanagersModelCollection"); } }
        [Association(@"KaryawansModelReferencesBranchesModel")]
        public XPCollection<KaryawansModel> KaryawansModelCollection { get { return GetCollection<KaryawansModel>("KaryawansModelCollection"); } }
    }

}
