//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace AutoDealer.DB.its_honda
{

    [Persistent(@"model_kendaraans")]
    public partial class ModelKendaraansModel : XPLiteObject
    {
        long fid;
        [Key(true)]
        public long id
        {
            get { return fid; }
            set { SetPropertyValue<long>("id", ref fid, value); }
        }
        string fmerk_kendaraan;
        [Size(255)]
        public string merk_kendaraan
        {
            get { return fmerk_kendaraan; }
            set { SetPropertyValue<string>("merk_kendaraan", ref fmerk_kendaraan, value); }
        }
        string ftipe_kendaraan;
        [Size(255)]
        public string tipe_kendaraan
        {
            get { return ftipe_kendaraan; }
            set { SetPropertyValue<string>("tipe_kendaraan", ref ftipe_kendaraan, value); }
        }
        string fvariant;
        [Size(255)]
        public string variant
        {
            get { return fvariant; }
            set { SetPropertyValue<string>("variant", ref fvariant, value); }
        }
        DateTime fcreatedAt;
        public DateTime createdAt
        {
            get { return fcreatedAt; }
            set { SetPropertyValue<DateTime>("createdAt", ref fcreatedAt, value); }
        }
        DateTime fupdatedAt;
        public DateTime updatedAt
        {
            get { return fupdatedAt; }
            set { SetPropertyValue<DateTime>("updatedAt", ref fupdatedAt, value); }
        }
        DateTime fdeletedAt;
        public DateTime deletedAt
        {
            get { return fdeletedAt; }
            set { SetPropertyValue<DateTime>("deletedAt", ref fdeletedAt, value); }
        }
        int fversion;
        public int version
        {
            get { return fversion; }
            set { SetPropertyValue<int>("version", ref fversion, value); }
        }
        [Association(@"ProspeksModelReferencesModelKendaraansModel")]
        public XPCollection<ProspeksModel> ProspeksModelCollection { get { return GetCollection<ProspeksModel>("ProspeksModelCollection"); } }
    }

}
