//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace AutoDealer.DB.its_honda
{

    [Persistent(@"sales")]
    public partial class SalesModel : XPLiteObject
    {
        long fid;
        [Key(true)]
        public long id
        {
            get { return fid; }
            set { SetPropertyValue<long>("id", ref fid, value); }
        }
        string fnama_sales;
        [Size(255)]
        public string nama_sales
        {
            get { return fnama_sales; }
            set { SetPropertyValue<string>("nama_sales", ref fnama_sales, value); }
        }
        DateTime fcreatedAt;
        public DateTime createdAt
        {
            get { return fcreatedAt; }
            set { SetPropertyValue<DateTime>("createdAt", ref fcreatedAt, value); }
        }
        DateTime fupdatedAt;
        public DateTime updatedAt
        {
            get { return fupdatedAt; }
            set { SetPropertyValue<DateTime>("updatedAt", ref fupdatedAt, value); }
        }
        DateTime fdeletedAt;
        public DateTime deletedAt
        {
            get { return fdeletedAt; }
            set { SetPropertyValue<DateTime>("deletedAt", ref fdeletedAt, value); }
        }
        int fversion;
        public int version
        {
            get { return fversion; }
            set { SetPropertyValue<int>("version", ref fversion, value); }
        }
        long fkaryawanId;
        [Indexed(Name = @"karyawanId")]
        public long karyawanId
        {
            get { return fkaryawanId; }
            set { SetPropertyValue<long>("karyawanId", ref fkaryawanId, value); }
        }
        long fsalesgradeId;
        [Indexed(Name = @"salesgradeId")]
        public long salesgradeId
        {
            get { return fsalesgradeId; }
            set { SetPropertyValue<long>("salesgradeId", ref fsalesgradeId, value); }
        }
        SalesheadsModel fsalesheadId;
        [Indexed(Name = @"salesheadId")]
        [Association(@"SalesModelReferencesSalesheadsModel")]
        public SalesheadsModel salesheadId
        {
            get { return fsalesheadId; }
            set { SetPropertyValue<SalesheadsModel>("salesheadId", ref fsalesheadId, value); }
        }
        [Association(@"ProspeksModelReferencesSalesModel")]
        public XPCollection<ProspeksModel> ProspeksModelCollection { get { return GetCollection<ProspeksModel>("ProspeksModelCollection"); } }
    }

}
