//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace AutoDealer.DB.its_honda
{

    [Persistent(@"zipcodes")]
    public partial class ZipcodesModel : XPLiteObject
    {
        long fzipCode;
        [Key]
        public long zipCode
        {
            get { return fzipCode; }
            set { SetPropertyValue<long>("zipCode", ref fzipCode, value); }
        }
        string fkecamatan_distrik;
        [Size(255)]
        public string kecamatan_distrik
        {
            get { return fkecamatan_distrik; }
            set { SetPropertyValue<string>("kecamatan_distrik", ref fkecamatan_distrik, value); }
        }
        string fkotaKabupaten;
        [Size(255)]
        public string kotaKabupaten
        {
            get { return fkotaKabupaten; }
            set { SetPropertyValue<string>("kotaKabupaten", ref fkotaKabupaten, value); }
        }
        string fibuKota;
        [Size(255)]
        public string ibuKota
        {
            get { return fibuKota; }
            set { SetPropertyValue<string>("ibuKota", ref fibuKota, value); }
        }
        DateTime fcreatedAt;
        public DateTime createdAt
        {
            get { return fcreatedAt; }
            set { SetPropertyValue<DateTime>("createdAt", ref fcreatedAt, value); }
        }
        DateTime fupdatedAt;
        public DateTime updatedAt
        {
            get { return fupdatedAt; }
            set { SetPropertyValue<DateTime>("updatedAt", ref fupdatedAt, value); }
        }
        DateTime fdeletedAt;
        public DateTime deletedAt
        {
            get { return fdeletedAt; }
            set { SetPropertyValue<DateTime>("deletedAt", ref fdeletedAt, value); }
        }
        int fversion;
        public int version
        {
            get { return fversion; }
            set { SetPropertyValue<int>("version", ref fversion, value); }
        }
        [Association(@"ProspeksModelReferencesZipcodesModel")]
        public XPCollection<ProspeksModel> ProspeksModelCollection { get { return GetCollection<ProspeksModel>("ProspeksModelCollection"); } }
    }

}
