//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace AutoDealer.DB.DMS
{

    [Persistent(@"branch")]
    public partial class BranchModel : XPLiteObject
    {
        string fbranch_name;
        [Size(255)]
        public string branch_name
        {
            get { return fbranch_name; }
            set { SetPropertyValue<string>("branch_name", ref fbranch_name, value); }
        }
        string falamat;
        [Size(400)]
        public string alamat
        {
            get { return falamat; }
            set { SetPropertyValue<string>("alamat", ref falamat, value); }
        }
        bool factive;
        public bool active
        {
            get { return factive; }
            set { SetPropertyValue<bool>("active", ref factive, value); }
        }
        string fno_telepon;
        [Size(255)]
        public string no_telepon
        {
            get { return fno_telepon; }
            set { SetPropertyValue<string>("no_telepon", ref fno_telepon, value); }
        }
        long fid;
        [Key(true)]
        public long id
        {
            get { return fid; }
            set { SetPropertyValue<long>("id", ref fid, value); }
        }
        [Association(@"UserHasBranchModelReferencesBranchModel")]
        public XPCollection<UserHasBranchModel> UserHasBranches { get { return GetCollection<UserHasBranchModel>("UserHasBranches"); } }
        [Association(@"UserHasBranchModelReferencesBranchModel1")]
        public XPCollection<UserHasBranchModel> UserHasBranches1 { get { return GetCollection<UserHasBranchModel>("UserHasBranches1"); } }
        [Association(@"UserModelReferencesBranchModel")]
        public XPCollection<UserModel> Users { get { return GetCollection<UserModel>("Users"); } }
        [Association(@"UnitPurchaseModelReferencesBranchModel")]
        public XPCollection<UnitPurchaseModel> UnitPurchases { get { return GetCollection<UnitPurchaseModel>("UnitPurchases"); } }
    }

}
