//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace AutoDealer.DB.DMS
{

    [Persistent(@"roles_has_permission")]
    public partial class RolesHasPermissionModel : XPLiteObject
    {
        long fid;
        [Key(true)]
        public long id
        {
            get { return fid; }
            set { SetPropertyValue<long>("id", ref fid, value); }
        }
        RolesModel frolename;
        [Size(255)]
        [Association(@"RolesHasPermissionModelReferencesRolesModel")]
        public RolesModel rolename
        {
            get { return frolename; }
            set { SetPropertyValue<RolesModel>("rolename", ref frolename, value); }
        }
        PermissionModel fpermission_name;
        [Size(255)]
        [Association(@"RolesHasPermissionModelReferencesPermissionModel")]
        public PermissionModel permission_name
        {
            get { return fpermission_name; }
            set { SetPropertyValue<PermissionModel>("permission_name", ref fpermission_name, value); }
        }
    }

}
