//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace AutoDealer.DB.DMS
{

    [Persistent(@"roles")]
    public partial class RolesModel : XPLiteObject
    {
        string frolename;
        [Key]
        [Size(255)]
        public string rolename
        {
            get { return frolename; }
            set { SetPropertyValue<string>("rolename", ref frolename, value); }
        }
        DateTime fcreated_at;
        public DateTime created_at
        {
            get { return fcreated_at; }
            set { SetPropertyValue<DateTime>("created_at", ref fcreated_at, value); }
        }
        string fcreated_by;
        [Size(255)]
        public string created_by
        {
            get { return fcreated_by; }
            set { SetPropertyValue<string>("created_by", ref fcreated_by, value); }
        }
        [Association(@"RolesHasPermissionModelReferencesRolesModel")]
        public XPCollection<RolesHasPermissionModel> RolesHasPermissions { get { return GetCollection<RolesHasPermissionModel>("RolesHasPermissions"); } }
        [Association(@"UserHasRolesModelReferencesRolesModel")]
        public XPCollection<UserHasRolesModel> UserHasRolesModelCollection { get { return GetCollection<UserHasRolesModel>("UserHasRolesModelCollection"); } }
    }

}
