//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace AutoDealer.DB.DMS
{

    [Persistent(@"roles_has_permission")]
    public partial class RolesHasPermissionModel : XPLiteObject
    {
        long fid;
        [Key(true)]
        public long id
        {
            get { return fid; }
            set { SetPropertyValue<long>("id", ref fid, value); }
        }
        string frolename;
        [Size(255)]
        public string rolename
        {
            get { return frolename; }
            set { SetPropertyValue<string>("rolename", ref frolename, value); }
        }
        string fpermission_name;
        [Size(255)]
        public string permission_name
        {
            get { return fpermission_name; }
            set { SetPropertyValue<string>("permission_name", ref fpermission_name, value); }
        }
    }

}
