//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace AutoDealer.DB.DMS
{

    [Persistent(@"unit_accessory")]
    public partial class UnitAccessoryModel : XPLiteObject
    {
        long fid;
        [Key(true)]
        public long id
        {
            get { return fid; }
            set { SetPropertyValue<long>("id", ref fid, value); }
        }
        string fkode_accessory;
        [Size(255)]
        public string kode_accessory
        {
            get { return fkode_accessory; }
            set { SetPropertyValue<string>("kode_accessory", ref fkode_accessory, value); }
        }
        string fnama_accessory;
        [Size(255)]
        public string nama_accessory
        {
            get { return fnama_accessory; }
            set { SetPropertyValue<string>("nama_accessory", ref fnama_accessory, value); }
        }
        string fcreated_by;
        [Size(255)]
        public string created_by
        {
            get { return fcreated_by; }
            set { SetPropertyValue<string>("created_by", ref fcreated_by, value); }
        }
        string fupdated_by;
        [Size(255)]
        public string updated_by
        {
            get { return fupdated_by; }
            set { SetPropertyValue<string>("updated_by", ref fupdated_by, value); }
        }
        DateTime fcreated_at;
        public DateTime created_at
        {
            get { return fcreated_at; }
            set { SetPropertyValue<DateTime>("created_at", ref fcreated_at, value); }
        }
        DateTime fupdated_at;
        public DateTime updated_at
        {
            get { return fupdated_at; }
            set { SetPropertyValue<DateTime>("updated_at", ref fupdated_at, value); }
        }
    }

}
