//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace AutoDealer.DB.DMS
{

    [Persistent(@"unit_purchase_detail")]
    public partial class UnitPurchaseDetailModel : XPLiteObject
    {
        long fid;
        [Key(true)]
        public long id
        {
            get { return fid; }
            set { SetPropertyValue<long>("id", ref fid, value); }
        }
        string fkode_pembelian;
        [Size(255)]
        public string kode_pembelian
        {
            get { return fkode_pembelian; }
            set { SetPropertyValue<string>("kode_pembelian", ref fkode_pembelian, value); }
        }
        long fmodel;
        public long model
        {
            get { return fmodel; }
            set { SetPropertyValue<long>("model", ref fmodel, value); }
        }
        long ftransmisi;
        public long transmisi
        {
            get { return ftransmisi; }
            set { SetPropertyValue<long>("transmisi", ref ftransmisi, value); }
        }
        long fvariant;
        public long variant
        {
            get { return fvariant; }
            set { SetPropertyValue<long>("variant", ref fvariant, value); }
        }
        long fwarna;
        public long warna
        {
            get { return fwarna; }
            set { SetPropertyValue<long>("warna", ref fwarna, value); }
        }
        string fcreated_by;
        [Size(255)]
        public string created_by
        {
            get { return fcreated_by; }
            set { SetPropertyValue<string>("created_by", ref fcreated_by, value); }
        }
        string fupdated_by;
        [Size(255)]
        public string updated_by
        {
            get { return fupdated_by; }
            set { SetPropertyValue<string>("updated_by", ref fupdated_by, value); }
        }
        DateTime fcreated_at;
        public DateTime created_at
        {
            get { return fcreated_at; }
            set { SetPropertyValue<DateTime>("created_at", ref fcreated_at, value); }
        }
        DateTime fupdated_at;
        public DateTime updated_at
        {
            get { return fupdated_at; }
            set { SetPropertyValue<DateTime>("updated_at", ref fupdated_at, value); }
        }
        decimal fharga;
        public decimal harga
        {
            get { return fharga; }
            set { SetPropertyValue<decimal>("harga", ref fharga, value); }
        }
        decimal fpotongan;
        public decimal potongan
        {
            get { return fpotongan; }
            set { SetPropertyValue<decimal>("potongan", ref fpotongan, value); }
        }
        decimal fdpp;
        public decimal dpp
        {
            get { return fdpp; }
            set { SetPropertyValue<decimal>("dpp", ref fdpp, value); }
        }
        decimal fppn;
        public decimal ppn
        {
            get { return fppn; }
            set { SetPropertyValue<decimal>("ppn", ref fppn, value); }
        }
        decimal ftotal;
        public decimal total
        {
            get { return ftotal; }
            set { SetPropertyValue<decimal>("total", ref ftotal, value); }
        }
        string fno_rangka;
        [Size(255)]
        public string no_rangka
        {
            get { return fno_rangka; }
            set { SetPropertyValue<string>("no_rangka", ref fno_rangka, value); }
        }
        string fno_mesin;
        [Size(255)]
        public string no_mesin
        {
            get { return fno_mesin; }
            set { SetPropertyValue<string>("no_mesin", ref fno_mesin, value); }
        }
    }

}
