//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace AutoDealer.DB.DMS
{

    [Persistent(@"unit_customer")]
    public partial class UnitCustomerModel : XPLiteObject
    {
        string fkode_customer;
        [Key]
        [Size(255)]
        public string kode_customer
        {
            get { return fkode_customer; }
            set { SetPropertyValue<string>("kode_customer", ref fkode_customer, value); }
        }
        string fnama_customer;
        [Size(255)]
        public string nama_customer
        {
            get { return fnama_customer; }
            set { SetPropertyValue<string>("nama_customer", ref fnama_customer, value); }
        }
        string fno_ktp;
        [Size(255)]
        public string no_ktp
        {
            get { return fno_ktp; }
            set { SetPropertyValue<string>("no_ktp", ref fno_ktp, value); }
        }
        string ftelepon;
        [Size(255)]
        public string telepon
        {
            get { return ftelepon; }
            set { SetPropertyValue<string>("telepon", ref ftelepon, value); }
        }
        string femail;
        [Size(255)]
        public string email
        {
            get { return femail; }
            set { SetPropertyValue<string>("email", ref femail, value); }
        }
        string falamat;
        [Size(255)]
        public string alamat
        {
            get { return falamat; }
            set { SetPropertyValue<string>("alamat", ref falamat, value); }
        }
        string fkecamatan;
        [Size(255)]
        public string kecamatan
        {
            get { return fkecamatan; }
            set { SetPropertyValue<string>("kecamatan", ref fkecamatan, value); }
        }
        string fkota_kabupaten;
        [Size(255)]
        public string kota_kabupaten
        {
            get { return fkota_kabupaten; }
            set { SetPropertyValue<string>("kota_kabupaten", ref fkota_kabupaten, value); }
        }
        string fprovinsi;
        [Size(255)]
        public string provinsi
        {
            get { return fprovinsi; }
            set { SetPropertyValue<string>("provinsi", ref fprovinsi, value); }
        }
        string fpekerjaan;
        [Size(255)]
        public string pekerjaan
        {
            get { return fpekerjaan; }
            set { SetPropertyValue<string>("pekerjaan", ref fpekerjaan, value); }
        }
        string fdetail_pekerjaan;
        [Size(255)]
        public string detail_pekerjaan
        {
            get { return fdetail_pekerjaan; }
            set { SetPropertyValue<string>("detail_pekerjaan", ref fdetail_pekerjaan, value); }
        }
        string fcreated_by;
        [Size(255)]
        public string created_by
        {
            get { return fcreated_by; }
            set { SetPropertyValue<string>("created_by", ref fcreated_by, value); }
        }
        string fupdated_by;
        [Size(255)]
        public string updated_by
        {
            get { return fupdated_by; }
            set { SetPropertyValue<string>("updated_by", ref fupdated_by, value); }
        }
        DateTime fcreated_at;
        public DateTime created_at
        {
            get { return fcreated_at; }
            set { SetPropertyValue<DateTime>("created_at", ref fcreated_at, value); }
        }
        DateTime fupdated_at;
        public DateTime updated_at
        {
            get { return fupdated_at; }
            set { SetPropertyValue<DateTime>("updated_at", ref fupdated_at, value); }
        }
        string fnpwp;
        [Size(255)]
        public string npwp
        {
            get { return fnpwp; }
            set { SetPropertyValue<string>("npwp", ref fnpwp, value); }
        }
        string fnama_npwp;
        [Size(255)]
        public string nama_npwp
        {
            get { return fnama_npwp; }
            set { SetPropertyValue<string>("nama_npwp", ref fnama_npwp, value); }
        }
    }

}
