//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace AutoDealer.DB.DMS
{

    [Persistent(@"unit_model_warna")]
    public partial class UnitModelWarnaModel : XPLiteObject
    {
        long fid_unit_warna;
        [Key(true)]
        public long id_unit_warna
        {
            get { return fid_unit_warna; }
            set { SetPropertyValue<long>("id_unit_warna", ref fid_unit_warna, value); }
        }
        string fkode_warna;
        [Size(255)]
        public string kode_warna
        {
            get { return fkode_warna; }
            set { SetPropertyValue<string>("kode_warna", ref fkode_warna, value); }
        }
        string fnama_warna;
        [Size(255)]
        public string nama_warna
        {
            get { return fnama_warna; }
            set { SetPropertyValue<string>("nama_warna", ref fnama_warna, value); }
        }
        long fid_model;
        public long id_model
        {
            get { return fid_model; }
            set { SetPropertyValue<long>("id_model", ref fid_model, value); }
        }
        long fid_variant;
        public long id_variant
        {
            get { return fid_variant; }
            set { SetPropertyValue<long>("id_variant", ref fid_variant, value); }
        }
        long fid_transmisi;
        public long id_transmisi
        {
            get { return fid_transmisi; }
            set { SetPropertyValue<long>("id_transmisi", ref fid_transmisi, value); }
        }
        string fcreated_by;
        [Size(255)]
        public string created_by
        {
            get { return fcreated_by; }
            set { SetPropertyValue<string>("created_by", ref fcreated_by, value); }
        }
        string fupdated_by;
        [Size(255)]
        public string updated_by
        {
            get { return fupdated_by; }
            set { SetPropertyValue<string>("updated_by", ref fupdated_by, value); }
        }
        DateTime fcreated_at;
        public DateTime created_at
        {
            get { return fcreated_at; }
            set { SetPropertyValue<DateTime>("created_at", ref fcreated_at, value); }
        }
        DateTime fupdated_at;
        public DateTime updated_at
        {
            get { return fupdated_at; }
            set { SetPropertyValue<DateTime>("updated_at", ref fupdated_at, value); }
        }
    }

}
