//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace AutoDealer.DB.DMS
{

    [Persistent(@"unit_purchase")]
    public partial class UnitPurchaseModel : XPLiteObject
    {
        string fkode_pembelian;
        [Key]
        [Size(255)]
        public string kode_pembelian
        {
            get { return fkode_pembelian; }
            set { SetPropertyValue<string>("kode_pembelian", ref fkode_pembelian, value); }
        }
        string fno_referensi;
        [Size(255)]
        public string no_referensi
        {
            get { return fno_referensi; }
            set { SetPropertyValue<string>("no_referensi", ref fno_referensi, value); }
        }
        string fkode_supplier;
        [Size(255)]
        public string kode_supplier
        {
            get { return fkode_supplier; }
            set { SetPropertyValue<string>("kode_supplier", ref fkode_supplier, value); }
        }
        DateTime ftanggal_pembelian;
        public DateTime tanggal_pembelian
        {
            get { return ftanggal_pembelian; }
            set { SetPropertyValue<DateTime>("tanggal_pembelian", ref ftanggal_pembelian, value); }
        }
        decimal fdpp_pembelian;
        public decimal dpp_pembelian
        {
            get { return fdpp_pembelian; }
            set { SetPropertyValue<decimal>("dpp_pembelian", ref fdpp_pembelian, value); }
        }
        decimal fppn_pembelian;
        public decimal ppn_pembelian
        {
            get { return fppn_pembelian; }
            set { SetPropertyValue<decimal>("ppn_pembelian", ref fppn_pembelian, value); }
        }
        decimal ftotal_pembelian;
        public decimal total_pembelian
        {
            get { return ftotal_pembelian; }
            set { SetPropertyValue<decimal>("total_pembelian", ref ftotal_pembelian, value); }
        }
        string fstatus;
        [Size(255)]
        public string status
        {
            get { return fstatus; }
            set { SetPropertyValue<string>("status", ref fstatus, value); }
        }
        string fcreated_by;
        [Size(255)]
        public string created_by
        {
            get { return fcreated_by; }
            set { SetPropertyValue<string>("created_by", ref fcreated_by, value); }
        }
        string fupdated_by;
        [Size(255)]
        public string updated_by
        {
            get { return fupdated_by; }
            set { SetPropertyValue<string>("updated_by", ref fupdated_by, value); }
        }
        DateTime fcreated_at;
        public DateTime created_at
        {
            get { return fcreated_at; }
            set { SetPropertyValue<DateTime>("created_at", ref fcreated_at, value); }
        }
        DateTime fupdated_at;
        public DateTime updated_at
        {
            get { return fupdated_at; }
            set { SetPropertyValue<DateTime>("updated_at", ref fupdated_at, value); }
        }
    }

}
