//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace AutoDealer.DB.DMS
{

    [Persistent(@"user")]
    public partial class UserModel : XPLiteObject
    {
        string fusername;
        [Key]
        [Size(255)]
        public string username
        {
            get { return fusername; }
            set { SetPropertyValue<string>("username", ref fusername, value); }
        }
        string fpassword;
        [Size(400)]
        public string password
        {
            get { return fpassword; }
            set { SetPropertyValue<string>("password", ref fpassword, value); }
        }
        bool factive;
        public bool active
        {
            get { return factive; }
            set { SetPropertyValue<bool>("active", ref factive, value); }
        }
        BranchModel fcurrent_branch;
        [Association(@"UserModelReferencesBranchModel")]
        public BranchModel current_branch
        {
            get { return fcurrent_branch; }
            set { SetPropertyValue<BranchModel>("current_branch", ref fcurrent_branch, value); }
        }
        string fcreated_by;
        [Size(255)]
        public string created_by
        {
            get { return fcreated_by; }
            set { SetPropertyValue<string>("created_by", ref fcreated_by, value); }
        }
        DateTime fcreated_at;
        public DateTime created_at
        {
            get { return fcreated_at; }
            set { SetPropertyValue<DateTime>("created_at", ref fcreated_at, value); }
        }
        string fperson_name;
        [Size(255)]
        public string person_name
        {
            get { return fperson_name; }
            set { SetPropertyValue<string>("person_name", ref fperson_name, value); }
        }
        [Association(@"UserHasBranchModelReferencesUserModel")]
        public XPCollection<UserHasBranchModel> UserHasBranches { get { return GetCollection<UserHasBranchModel>("UserHasBranches"); } }
        [Association(@"UserHasRolesModelReferencesUserModel")]
        public XPCollection<UserHasRolesModel> UserHasRolesModelCollection { get { return GetCollection<UserHasRolesModel>("UserHasRolesModelCollection"); } }
    }

}
