//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace AutoDealer.DB.DMS
{

    [Persistent(@"user_has_roles")]
    public partial class UserHasRolesModel : XPLiteObject
    {
        UserModel fusername;
        [Size(255)]
        [Association(@"UserHasRolesModelReferencesUserModel")]
        public UserModel username
        {
            get { return fusername; }
            set { SetPropertyValue<UserModel>("username", ref fusername, value); }
        }
        RolesModel frolename;
        [Size(255)]
        [Association(@"UserHasRolesModelReferencesRolesModel")]
        public RolesModel rolename
        {
            get { return frolename; }
            set { SetPropertyValue<RolesModel>("rolename", ref frolename, value); }
        }
        long fid;
        [Key(true)]
        public long id
        {
            get { return fid; }
            set { SetPropertyValue<long>("id", ref fid, value); }
        }
    }

}
